SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[HasChildTab]
(
   @TabId   Int
) 
	RETURNS Bit
AS
BEGIN
    RETURN CASE WHEN EXISTS (SELECT 1 FROM dbo.Tabs WHERE ParentId = @TabId) THEN 1 ELSE 0 END
END
GO
