CREATE TABLE [dbo].[Urls]
(
[UrlID] [int] NOT NULL IDENTITY(1, 1),
[PortalID] [int] NULL,
[Url] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Urls] ADD CONSTRAINT [PK_Urls] PRIMARY KEY CLUSTERED  ([UrlID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Urls] ADD CONSTRAINT [IX_Urls] UNIQUE NONCLUSTERED  ([Url], [PortalID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Urls] ADD CONSTRAINT [FK_Urls_Portals] FOREIGN KEY ([PortalID]) REFERENCES [dbo].[Portals] ([PortalID]) ON DELETE CASCADE
GO
